### ISSUE TITLE
Popularization checklist

### ISSUE THREAD

**Issue by ayld** [ayld/Facade#45]
This checklist will become tasks when we decide what exactly we need.

This is intended as a discussion on what we need:
- [x] [Change the name](https://github.com/ayld/Facade/issues/49)
- [x] [Create GitHub organization](https://github.com/ayld/Facade/issues/46)
- [x] [Switch to LGPL](https://github.com/ayld/Facade/issues/48)
- [ ] [Organization and project logo](https://github.com/ayld/Facade/issues/50)
- [ ] Better site
- [ ] Maven plugin deployed to a repo
- [ ] Demo project: pretty example with many graphs showcasing how a project with 50 libs becomes a project with 1
